// <auto-generated />
using Catalog.Persistence.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Persistence.DataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Description product 1",
                            Name = "Product 1",
                            Price = 271m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Description product 2",
                            Name = "Product 2",
                            Price = 276m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Description product 3",
                            Name = "Product 3",
                            Price = 720m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Description product 4",
                            Name = "Product 4",
                            Price = 116m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Description product 5",
                            Name = "Product 5",
                            Price = 681m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = "Description product 6",
                            Name = "Product 6",
                            Price = 216m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = "Description product 7",
                            Name = "Product 7",
                            Price = 355m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "Description product 8",
                            Name = "Product 8",
                            Price = 922m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = "Description product 9",
                            Name = "Product 9",
                            Price = 871m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Description product 10",
                            Name = "Product 10",
                            Price = 292m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = "Description product 11",
                            Name = "Product 11",
                            Price = 214m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = "Description product 12",
                            Name = "Product 12",
                            Price = 853m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = "Description product 13",
                            Name = "Product 13",
                            Price = 200m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = "Description product 14",
                            Name = "Product 14",
                            Price = 303m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = "Description product 15",
                            Name = "Product 15",
                            Price = 425m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = "Description product 16",
                            Name = "Product 16",
                            Price = 998m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = "Description product 17",
                            Name = "Product 17",
                            Price = 412m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = "Description product 18",
                            Name = "Product 18",
                            Price = 231m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = "Description product 19",
                            Name = "Product 19",
                            Price = 308m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = "Description product 20",
                            Name = "Product 20",
                            Price = 203m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = "Description product 21",
                            Name = "Product 21",
                            Price = 507m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = "Description product 22",
                            Name = "Product 22",
                            Price = 588m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = "Description product 23",
                            Name = "Product 23",
                            Price = 671m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = "Description product 24",
                            Name = "Product 24",
                            Price = 447m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = "Description product 25",
                            Name = "Product 25",
                            Price = 768m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = "Description product 26",
                            Name = "Product 26",
                            Price = 284m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = "Description product 27",
                            Name = "Product 27",
                            Price = 676m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = "Description product 28",
                            Name = "Product 28",
                            Price = 581m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = "Description product 29",
                            Name = "Product 29",
                            Price = 211m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = "Description product 30",
                            Name = "Product 30",
                            Price = 515m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = "Description product 31",
                            Name = "Product 31",
                            Price = 750m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = "Description product 32",
                            Name = "Product 32",
                            Price = 136m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = "Description product 33",
                            Name = "Product 33",
                            Price = 879m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = "Description product 34",
                            Name = "Product 34",
                            Price = 121m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = "Description product 35",
                            Name = "Product 35",
                            Price = 712m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = "Description product 36",
                            Name = "Product 36",
                            Price = 597m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = "Description product 37",
                            Name = "Product 37",
                            Price = 692m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = "Description product 38",
                            Name = "Product 38",
                            Price = 990m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = "Description product 39",
                            Name = "Product 39",
                            Price = 729m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = "Description product 40",
                            Name = "Product 40",
                            Price = 127m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = "Description product 41",
                            Name = "Product 41",
                            Price = 507m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = "Description product 42",
                            Name = "Product 42",
                            Price = 666m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = "Description product 43",
                            Name = "Product 43",
                            Price = 473m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = "Description product 44",
                            Name = "Product 44",
                            Price = 562m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = "Description product 45",
                            Name = "Product 45",
                            Price = 511m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = "Description product 46",
                            Name = "Product 46",
                            Price = 290m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = "Description product 47",
                            Name = "Product 47",
                            Price = 298m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = "Description product 48",
                            Name = "Product 48",
                            Price = 155m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = "Description product 49",
                            Name = "Product 49",
                            Price = 724m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = "Description product 50",
                            Name = "Product 50",
                            Price = 390m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = "Description product 51",
                            Name = "Product 51",
                            Price = 921m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = "Description product 52",
                            Name = "Product 52",
                            Price = 598m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = "Description product 53",
                            Name = "Product 53",
                            Price = 912m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = "Description product 54",
                            Name = "Product 54",
                            Price = 299m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = "Description product 55",
                            Name = "Product 55",
                            Price = 845m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = "Description product 56",
                            Name = "Product 56",
                            Price = 683m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = "Description product 57",
                            Name = "Product 57",
                            Price = 605m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = "Description product 58",
                            Name = "Product 58",
                            Price = 372m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = "Description product 59",
                            Name = "Product 59",
                            Price = 348m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = "Description product 60",
                            Name = "Product 60",
                            Price = 496m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = "Description product 61",
                            Name = "Product 61",
                            Price = 539m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = "Description product 62",
                            Name = "Product 62",
                            Price = 774m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = "Description product 63",
                            Name = "Product 63",
                            Price = 811m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = "Description product 64",
                            Name = "Product 64",
                            Price = 456m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = "Description product 65",
                            Name = "Product 65",
                            Price = 542m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = "Description product 66",
                            Name = "Product 66",
                            Price = 177m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = "Description product 67",
                            Name = "Product 67",
                            Price = 973m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = "Description product 68",
                            Name = "Product 68",
                            Price = 178m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = "Description product 69",
                            Name = "Product 69",
                            Price = 590m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = "Description product 70",
                            Name = "Product 70",
                            Price = 827m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = "Description product 71",
                            Name = "Product 71",
                            Price = 405m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = "Description product 72",
                            Name = "Product 72",
                            Price = 421m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = "Description product 73",
                            Name = "Product 73",
                            Price = 501m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = "Description product 74",
                            Name = "Product 74",
                            Price = 281m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = "Description product 75",
                            Name = "Product 75",
                            Price = 695m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = "Description product 76",
                            Name = "Product 76",
                            Price = 840m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = "Description product 77",
                            Name = "Product 77",
                            Price = 215m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = "Description product 78",
                            Name = "Product 78",
                            Price = 208m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = "Description product 79",
                            Name = "Product 79",
                            Price = 935m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = "Description product 80",
                            Name = "Product 80",
                            Price = 577m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = "Description product 81",
                            Name = "Product 81",
                            Price = 985m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = "Description product 82",
                            Name = "Product 82",
                            Price = 621m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = "Description product 83",
                            Name = "Product 83",
                            Price = 857m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = "Description product 84",
                            Name = "Product 84",
                            Price = 820m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = "Description product 85",
                            Name = "Product 85",
                            Price = 593m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = "Description product 86",
                            Name = "Product 86",
                            Price = 252m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = "Description product 87",
                            Name = "Product 87",
                            Price = 224m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = "Description product 88",
                            Name = "Product 88",
                            Price = 680m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = "Description product 89",
                            Name = "Product 89",
                            Price = 276m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = "Description product 90",
                            Name = "Product 90",
                            Price = 129m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = "Description product 91",
                            Name = "Product 91",
                            Price = 992m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = "Description product 92",
                            Name = "Product 92",
                            Price = 419m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = "Description product 93",
                            Name = "Product 93",
                            Price = 742m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = "Description product 94",
                            Name = "Product 94",
                            Price = 332m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = "Description product 95",
                            Name = "Product 95",
                            Price = 587m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = "Description product 96",
                            Name = "Product 96",
                            Price = 733m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = "Description product 97",
                            Name = "Product 97",
                            Price = 855m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = "Description product 98",
                            Name = "Product 98",
                            Price = 117m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = "Description product 99",
                            Name = "Product 99",
                            Price = 120m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ProductInStockId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 85
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 76
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 85
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 87
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 60
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 39
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 88
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 49
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 63
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 60
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 83
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 79
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 65
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 64
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 97
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 57
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 22
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 82
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 98
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 80
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 62
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 25
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 57
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 56
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 62
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 66
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 91
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 55
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 84
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 56
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 61
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 57
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 31
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 93
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 63
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 87
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 74
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 49
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 96
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 44
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 86
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 80
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 79
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 20
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 72
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 54
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 52
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 30
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 53
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 97
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
